spring:
  profiles:
    include: redis
  redis:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
    port: 6379
    host: 127.0.0.1
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/redisDB?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update